
// Auto-generated by AutoPilot on 29-07-2023 at 03:14:05

const express = require('express');
const router = express.Router();

// Create router for GET /dan route
router.get('/dan', (req, res) => {
    // Create an array of the last 3 books written by Dan Brown 
    const books = ["The Da Vinci Code", "Angels & Demons", "Inferno"];
    
    res.json(books);
});

module.exports = router;